### ISSUE TITLE
Separate ext-srcs from main application

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#11]
The original authors intended the `ext-srcs` app to function as a separate application.  It has an API that is called by the core PSM app.  In the code's current state, the two apps aren't fully separated.  Their implementation is still closely coupled.  In the future, these might be disentangled.

If they are separated to the point where they can be deployed separately, then the `ext-srcs` app could be used to wrap external data sources for other applications, not just the PSM.  At that point, `ext-srcs` should be moved to its own repository.

**Comment by jvasile** [comment]
Just to bring some of the offline discussion where it can be seen by others:

@kfogel has made arguments for replacing external sources with an ETL app and then replacing the calls to ext-srcs functionality with database calls.  E.g. he wants to skip the API stuff since that's more stuff to maintain.

@jasonaowen has made some arguments for keeping the separation.  For one, we might want to serve some of that data in different slices to different states.  E.g. states have access to different subsets of sources but we maintain just one external sources stack and one db of that source data.  We might also want to serve some parts of that data to other projects.

**Comment by kfogel** [comment]
IOW, it sounds like @jasonaowen is making the (quite reasonable) argument that we might have a lot of business logic involved in serving/filtering data from external sources, depending on who's requesting it, and that that is easier done through a dedicated authz-integrated API than through straight DB permissions and SQL.

I think in the process of summarizing his argument, I may have convinced myself that he's right :-).  @jasonaowen, was that basically accurate?

**Comment by cecilia-donnelly** [comment]
See also #35 for some discussion about external sources.  @slifty will follow up on the list with some possible paths forward on this.

**Comment by jasonaowen** [comment]
@kfogel yes, that is a an excellent summary. :)

**Comment by jvasile** [comment]
As with [Issue 35](https://github.com/OpenTechStrategies/psm/issues/35), after @slifty's analysis that the existing ext-sources code is a dead end, I'm closing this. Related: [my PR proposing we rm this app entirely](https://github.com/OpenTechStrategies/psm/pull/68).
