### ISSUE TITLE
Service admin can edit/delete other users' accounts

### ISSUE THREAD

**Issue by brainwane** [OpenTechStrategies/psm#149]
If I am logged in as a service admin, the list of Service Agents I see sometimes lets me see the list of all PSM users, and to edit or delete those user accounts. Also, there's a URL that I can get to that lets me edit the system administrator's account.

To reproduce:
* Log in as a service admin.
* Go to `cms/admin/viewAgents` in the browser .
* Create an agent.
* Delete that agent (either by clicking the Delete link in the Action column, or by checking the checkbox for that agent and choosing Delete Selected Agents).
* Confirm that deletion.

Result:
* The list labelled Service Agents at `cms/admin/viewAgents` now actually contains all user accounts, including system administrators and providers, and offers you the ability to Edit or Delete them. The PSM does save the changes made to those user accounts' first name, last name, and email address, or, in the case of deletion, does accept the deletion (asking whether you're sure you want to delete that "system agent").

* Going directly to `cms/admin/beginEditAgent?userId=SYSTEM` lets me view and edit the system administrator account's user information.

_Note: because the PSM is not being used in production by anyone (as far as we know), we decided to track this as a public GitHub issue. But, had the PSM been further along, the issue would be handled confidentially, per #92._

**Comment by brainwane** [comment]
[I happened to encounter this bug again today on master, so it's still happening.]

**Comment by brainwane** [comment]
[This is still reproducible on `master` as of today.]

**Comment by cecilia-donnelly** [comment]
@jasonaowen and I talked about this and don't see any reason for service admins to have access to *any* user accounts, even the service agents.  Do we have any requirements around this?  The discussions we've been having in #10 about the role of service agents suggest that they'll create their own accounts, much like providers.  

Unless we hear otherwise, the plan is to remove the ability of service admins to view *any* users, including agents, which will resolve this issue.
