### ISSUE TITLE
Upgrade Spring

### ISSUE THREAD

**Issue by brainwane** [OpenTechStrategies/psm#219]
Per `DEPENDENCIES.md`, we're currently using Spring 3.0.5, which was released 2010-10-20. If we're going to continue to use the 3.x series, we should upgrade to 3.2.18 -- see, for instance, [this post](https://spring.io/blog/2016/12/22/cve-2016-9879-spring-security-3-2-10-4-1-4-4-2-1-released) about a vulnerability that a later version of the Spring Framework addresses.

**Comment by jasonaowen** [comment]
The [migration guide for 3.2.18](http://docs.spring.io/spring/docs/3.2.18.RELEASE/spring-framework-reference/htmlsingle/#migration-3.1) suggests that there are no major changes (which is good since it's a minor version change), so we should do that upgrade soon. I suggest at least trying to upgrade to the latest 3.x series before upgrading major versions, in the hope that the minor version is easy and in the fear that the major version will be hard.

**Comment by brainwane** [comment]
For #30 I was looking at [Springfox](https://springfox.github.io/springfox/docs/current/), which depends on a component that's only in Spring version 4 and up (https://github.com/springfox/springfox/issues/938, https://github.com/springfox/springfox/issues/921 ). This is not by itself sufficient reason to upgrade but I predict there will be other tools and libraries we'll want to use that don't work with Spring 3.x, which would be reasons to upgrade to Spring to 4.x or above.

**Comment by jasonaowen** [comment]
[The version of `spring-mvc` we're using has a security issue](https://www.versioneye.com/java/org.springframework:spring-webmvc/3.0.5.RELEASE). I am not sure if the way this project uses spring-mvc exposes us to the vulnerability, but since we're already planning on upgrading, our time is probably better spent on the upgrade than on determining if we are vulnerable.

**Comment by jasonaowen** [comment]
Upgrading from our current version (`3.0.5.RELEASE`) is unfortunately not as easy as updating our `build.gradle` file.

Spring seems to be divided into two main sets of libraries: Spring Core and Spring Security. I tried upgrading each independently, but neither worked as-is. Upgrading Spring Core to `3.2.18.RELEASE` fails to deploy with a stack trace; upgrading Spring Security to `3.2.10.RELEASE` fails to deploy due to required configuration changes:

> You cannot use a spring-security-2.0.xsd or spring-security-3.0.xsd or spring-security-3.1.xsd schema with Spring Security 3.2. Please update your schema declarations to the 3.2 schema.

I'm sure both can be addressed, and might even be easy, but until this is top priority I don't want to spend more time than "is this a trivial upgrade?" takes.

**Comment by cecilia-donnelly** [comment]
@jasonaowen mentioned that newer versions of `spring-security` have some built-in support for ABAC.  There is a [blog post and example project on DZone](https://dzone.com/articles/simple-attribute-based-access-control-with-spring).  We're going to update Spring to take advantage of these features before turning to ABAC, as discussed in #10.

**Comment by jasonaowen** [comment]
I timeboxed my attempt to upgrade the Spring framework to 5.0.x, and wasn't able to successfully deploy it in a few hours. There seems to be some kind of problem with its optional dependency on a newer version of the `jackson` library. If that is the root problem here, possible resolutions include:

- Waiting for a newer version of Spring, which specifies its dependency
- Using a newer version of WildFly, which might bundle a newer version of jackson (see #520)

Either way, Spring 4.3.x is supposed to be supported until 2020 (at least, according to [a wiki page](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#dropped-support)), so we are not yet up against time pressure in that respect.

@cecilia-donnelly I suggest that it would be useful to keep an open issue for the Spring 5 upgrade (and, soon, the [Spring Security 5](https://spring.io/blog/2017/11/01/spring-security-5-0-0-rc1-released) upgrade); do you think that should be this issue or a new issue?

**Comment by cecilia-donnelly** [comment]
@jasonaowen thank you for this clear summary!  I like the idea of closing this one and opening a different one -- we've upgraded from the insecure, unsupported version of Spring we were on.  Upgrading to 5 is a more optional change that we can handle down the line.  Since it's a different kind of issue, I'd rather not lump them together.  If that seems reasonable, I'll open the new one pointing back to this issue.

**Comment by jasonaowen** [comment]
@cecilia-donnelly sounds good. I'll mark #522 as resolving this issue, so that it will close when the PR is merged.
