### ISSUE TITLE
Set up continuous deployment

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#222]
Now that we have Travis set up for CI, we should take the next step and automate deployments to a testing server.  This will allow us to always do manual testing against the most up-to-date code, without needing to constantly refresh our local instances.

**Comment by slifty** [comment]
A brief update -- CD will leverage [Jenkins](http://jenkins.io) to trigger the various pieces of deployment.  The basic steps for setting up a CD server are straightforward:

1) Run the install script on the server
2) Install Jenkins (jekins.io)
3) Install Gradle Plugin (https://wiki.jenkins.io/display/JENKINS/Gradle+Plugin)
4) Set up project in Jenkins

As we add things like code coverage tests and others we will need to update the CD script (likely in the form of adding plugins).  For our purposes since we are simply talking about a single CD server for demonstration things will be pretty straightforward -- in a more complex production environment we might need additional steps.

One concern I have right now is around migrations -- for CD to work we need to be able to ensure that the same deployment command will always work, even if we change the schema.  I'll catch up with the team tomorrow to get a better sense of where we stand with schema management today.

**Comment by cecilia-donnelly** [comment]
Thanks for this, @slifty.

Is it going to be an issue if we use both Travis and Jenkins?  (Asking because that might have implications for #243.)

We don't have a good system for schema management right now, as far as I know (right @jasonaowen, @BenGalewsky?).   This is a good push to get that set up.

**Comment by jasonaowen** [comment]
> Is it going to be an issue if we use both Travis and Jenkins?

GitHub allows for a large number of integrations; from that angle, there is no problem using both. The larger question, in my mind, is: does it make sense to use both?

Jenkins allows us to have more control over the build environment and job configuration, but the trade-off is we have to maintain our own instance. If we set up a Jenkins instance, do we still want to use Travis CI? Tasks like #243 might be easier in Jenkins, as could other CI things.

On the other hand, I don't think there is anything about setting up continuous deployment that requires Jenkins; I have seen it done with Travis. What is the motivation for using Jenkins instead of Travis?

(To be clear, I am fine with both Travis and Jenkins; I have used and like each. I would just like for us to be clear on why we are introducing additional dependencies & infrastructure.)

**Comment by slifty** [comment]
I just realized my reasons for skipping over Travis were flawed -- Travis does supports continuous deployment to the following service providers out of the box / without requiring any custom scripts to be include:  https://docs.travis-ci.com/user/deployment/

I was thinking that since we didn't want to lock into those providers we would want something that can be set up on any server we would want to deploy to.

Travis has the ability to write (custom deploy scripts)[https://docs.travis-ci.com/user/deployment/custom/], however.  This means we can write a custom script to deploy to whatever servers we want; the pro and the con is that this centralizes the deploy script into the repository.  My concern was that it would mean we are baking external infrastructure into our code base, but that can surely be mitigated in the execution (e.g. using environment variables in the deploy script)

I'll stick with Travis for now, and if we decide we don't like it we can add documentation explaining how to set up Jenkins for one-off CD servers.

**Comment by jasonaowen** [comment]
> We don't have a good system for schema management right now

I agree. Our schema management currently consists of three SQL files that we run on every deploy, preferably prefaced by a `DROP OWNED BY current_user`. This is stable and repeatable, but does not lend itself well to long-term users of the system. On the plus side, I think (hope) we're about at a place where schema modifications are infrequent.

@jvasile and I had talked about using [Liquibase](http://www.liquibase.org/) for migrations (#254). This will be critical once we have production deployments, as obviously we cannot ask people to throw away their existing data, and manual deployment steps require extensive documentation and are prone to error.

This could be a good time to invest it setting up Liquibase, but I don't think this issue should be blocked on it - we can start by recreating the database on every deploy, and change to Liquibase once that's set up.

**Comment by cecilia-donnelly** [comment]
We have CD running -- thanks @slifty!  Closing.
