### ISSUE TITLE
Set up first example of embedded help

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#265]
@brainwane discussed the need for embedded (tooltip-type) help in #195.

>- In-app context-sensitive help
>  This depends on the frontend libraries and frameworks we use; James suggested it would be nice if we could in some way reuse stuff from a central knowledge base. [Read the Docs content embedding via JavaScript](https://docs.readthedocs.io/en/latest/features/embed.html) via JavaScript might be something to consider.

When a user is completing a form on a page (for example), we should offer a tooltip for each field that describes what we expect the content of that field to look like.  For example, a tooltip for "NPI" might say something like "National Provider Identifier" and describe where a provider can get an NPI.

The to-do's for this issue are:
1. Should we use a framework like the RTD one Sumana mentioned?  If so, which one?  We'd like to reuse text in the tooltips and standalone documentation, and keep them up to date with each other.
2. Create a tooltip for a field.

**Comment by brainwane** [comment]
I started work on this by getting familiar with setting up a brand-new Read the Docs project with a few placeholder pages of documentation, which I've been able to do; next I'll start a branch with the PSM that includes some documents that build to Read the Docs, and uses the JavaScript content embedding approach.

**Comment by brainwane** [comment]
Further thought, investigation, and conversation with @jasonaowen later:

* I don't want to use JavaScript to embed content in the PSM from ReadTheDocs because that introduces a network dependency; what if the user's behind a firewall, for instance?
* I want to use ReStructuredText for user help docs, at least at first, because Sphinx works well with it (building it into HTML) and the ReadTheDocs workflow works well with Sphinx. Any new build step, though, will have to also include a Gradle change.
* Whatever templating system we use (sticking with JSP, moving to Jinja, or other), we'll have to implement *some* way for the user to hover/click/select the embedded/inline/tooltip/hover/contextual help. And that's going to be its own kind of tough thing, and it'd be good to figure out how to do that *first* (and submit a PR for it first).

So I'm going to try this:
* hand-write a small HTML file with "What's an NPI?" help text in `psm-app/cms-web/WebContent/WEB-INF/pages/`
* figure out how to get a JSP file to transclude this HTML file as hover text on a relevant `<span>` or a similar element, e.g., the NPI chunk of `psm-app/cms-web/WebContent/WEB-INF/pages/provider/enrollment/steps/pageTemplates/default/personal_information.jsp` [and submit this as a PR]
* write an `.rst` file containing that "What's an NPI?" help text
* get Sphinx to build that to an HTML file that lives in a directory in `psm-app/cms-web/WebContent/WEB-INF/pages/`
* get `personal_information.jsp` to transclude that file

**Comment by brainwane** [comment]
![npi-label-wip](https://user-images.githubusercontent.com/842790/28482436-555e8ade-6e36-11e7-83e2-fccbca05dfee.png)
Progress!

**Comment by brainwane** [comment]
I'd like to make my contextual help more helpful than an unstyled title element can be. For instance, in the NPI contextual help, I'd like to actually provide a clickable link to https://nppes.cms.hhs.gov/ .

So I am going to poke around a little and see if there is *any* existing tooling for providing contextual anything anywhere within the templates.

**Comment by brainwane** [comment]
I did some searching and I can't find any existing tooling within the PSM for providing richer contextual help.

* An element like `<details>` would be awesome, but [Internet Explorer doesn't support it](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#Browser_compatibility). (This investigation led to me filing #298.)
* Rich tooltip solutions ([1](https://stackoverflow.com/questions/40531029/how-to-create-a-pure-css-tooltip-with-html-content-for-inline-elements?rq=1), [2](https://stackoverflow.com/questions/7117073/how-to-add-a-tooltip-to-a-div), [3](https://gist.github.com/csasbach/867744)) basically always require JavaScript/CSS beyond my current fluency or, like, [a special Java library](https://dzone.com/articles/using-jsp-custom-tags-enable-h).

So here's my current plan:
* For pure abbreviations, the `<abbr>` [tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr) will probably be my go-to.
* We're going to use plaintext for the contextual help for now.
* I'll write a sample admin doc, which will be longer than a piece of embedded help would be, and then start on the Sphinx-and-RTD side of this issue.

**Comment by jasonaowen** [comment]
> An element like `<details>` would be awesome, but Internet Explorer doesn't support it.

If IE/Edge support is important, and we want to use `<details>`, we may be able to use a polyfill. [There are several JavaScript libraries available on GitHub](https://github.com/search?q=details%20polyfill), although none of them seem like a clear winner to me.

For the sake of evaluating compatibility, we're currently using jquery-1.7.1.

**Comment by brainwane** [comment]
I'm working on the assumption that the list of admin help topics I made in https://github.com/OpenTechStrategies/psm/issues/195#issuecomment-313782189 is reasonable. I'm working on "Which enrollment information the provider or service agent can modify or delete, and which enrollment information the service admin can modify or delete" for now. (I recognize that the precise content there will change over time; I'm picking this topic because it's something I can test locally and it's for service admins.)

**Comment by brainwane** [comment]
I have just found a tooltip implementation in the PSM, in the organizational enrollment workflow, in `psm-app/cms-web/WebContent/WEB-INF/pages/provider/enrollment/steps/pageTemplates/default/ownership_information.jsp`, where there's a question mark character next to "Type" that, when clicked, causes a pop-up with definitions:

![org-contextual-hint-question-mark](https://user-images.githubusercontent.com/842790/29690346-9e9a7fb8-88f4-11e7-8c60-6d22ffaa3213.png)
![definitions-org-enrollment](https://user-images.githubusercontent.com/842790/29690347-9e9bf53c-88f4-11e7-98b4-6fe6243a37b3.png)
